FISH-663 HK2 Upgrade - Exception Type Parsing
payara/patched-src-hk2 pull request #19
Opened 2020-12-22 09:45 UTC by MattGill98

2020-12-22 12:26 UTC, Pandrex247 requested changes
One of the build tests seems to now fail when it didn't before:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.glassfish.hk2.classmodel.reflect.impl.TypeImplTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.024 s - in org.glassfish.hk2.classmodel.reflect.impl.TypeImplTest
[INFO] Running org.glassfish.hk2.classmodel.reflect.test.method.MethodTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.039 s <<< FAILURE! - in org.glassfish.hk2.classmodel.reflect.test.method.MethodTest
[ERROR] simpleTest(org.glassfish.hk2.classmodel.reflect.test.method.MethodTest)  Time elapsed: 0.039 s  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
        at org.glassfish.hk2.classmodel.reflect.test.method.MethodTest.simpleTest(MethodTest.java:87)

[INFO] Running org.glassfish.hk2.classmodel.reflect.test.LocatorTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in org.glassfish.hk2.classmodel.reflect.test.LocatorTest
[INFO] Running org.glassfish.hk2.classmodel.reflect.test.ModelTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.glassfish.hk2.classmodel.reflect.test.ModelTest
[INFO] Running org.glassfish.hk2.classmodel.reflect.test.GFInstallationTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in org.glassfish.hk2.classmodel.reflect.test.GFInstallationTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   MethodTest.simpleTest:87 expected:<1> but was:<0>
[INFO]
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 2
```

2020-12-22 13:11 UTC, MattGill98 commented
@Pandrex247 Whoops, looks like I had uncommitted code (only in the tests though). I've redeployed https://github.com/payara/patched-src-hk2/pull/19

2020-12-22 14:59 UTC, Pandrex247 approved these changes
One of the build test seems to now fail on your branch

2020-12-23 10:07 UTC, merged

2021-04-09 03:59 UTC, jGauravGupta commented
Upstream repository missing this PR.